name: Render Map

on:
  push:
    branches:
      - main

jobs:
  update-map:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download unmined binary
        run: |
          wget https://unmined.net/download/unmined-cli-linux-x64-dev/?tmstv=$(date +%s) -O unmined.tar.gz
          mkdir unmined
          tar -xvf unmined.tar.gz --strip-components=1 -C ./unmined

      - name: Render overworld map
        run: |
          ./unmined/unmined-cli web render --world .map --dimension overworld --output .

      - name: Render caves map
        run: |
          ./unmined/unmined-cli web render --world .map --dimension overworld --gndxray true --output ./caves

      - name: Render nether map
        run: |
          ./unmined/unmined-cli web render --world .map --dimension nether --output ./nether

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Map Update"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}